version: '2'

services:
  number:
    image: salmanshaik8/numbers
    port:
      - 9000:8000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://salmans:password@db:5432/postgres
      - PORT=8000
  db:
    image: postgres:9.6
    port:
      - 5432:5432
    environment:
      - POSTGRES_USER=salmans
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
