version: "3"

services:
  db:
    image: postgres:latest
  web:
    build: .
    links:
      - db
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/postgres
